QT_MKSPEC_PATH = "qt4/mkspecs/${MACHINE}"
QT_MKSPEC = "${QT_MKSPEC_PATH}/qmake.conf"
QT_MKSPEC_CROSS_PATH = "${STAGING_DATADIR_NATIVE}/${QT_MKSPEC_PATH}"
QT_MKSPEC_CROSS = "${QT_MKSPEC_CROSS_PATH}/qmake.conf"
