PACKAGES = "dpkg"
PROVIDES = "dpkg"
SRC_URI = " \
	http://archive.raspbian.org/raspbian/pool/main/d/dpkg/dpkg_1.16.16+rpi1_armhf.deb;unpack=0;name=deb0\
"
DEBFILENAME_dpkg = "dpkg_1.16.16+rpi1_armhf.deb"
SRC_URI[deb0.sha256sum] = "4f2b19fae64b0d5a7d6850540f28b2a7e231af7219f5cd5c97e01b4c1c785046"
SRC_URI[deb0.md5sum] = "1b00c6bad2e15721d30b373031e58288"


inherit deb_group

# Prebuilt binaries, no need for any default dependencies
INHIBIT_DEFAULT_DEPS = "1"
INHIBIT_PACKAGE_STRIP = "1"
INSANE_SKIP_${PN} += "already-stripped"

FILES_${PN} = " \
	./usr/share/man/man1/dpkg-split.1.gz \
	./usr/share/locale/ja/LC_MESSAGES/ \
	./usr/share/locale/hu/LC_MESSAGES/ \
	./usr/share/locale/eo/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/ku/LC_MESSAGES/ \
	./usr/share/locale/lt/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/it/ \
	./usr/share/man/sv/man1/dpkg.1.gz \
	./usr/bin/dpkg-trigger \
	./usr/share/locale/km/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/ru/LC_MESSAGES/ \
	./usr/share/locale/ru/LC_MESSAGES/dpkg.mo \
	./usr/share/man/ja/man1/dpkg-split.1.gz \
	./usr/share/man/man8/start-stop-daemon.8.gz \
	./usr/bin/dpkg-maintscript-helper \
	./usr/share/locale/tl/LC_MESSAGES/ \
	./usr/sbin/dpkg-divert \
	./usr/share/man/pl/man5/dpkg.cfg.5.gz \
	./usr/share/man/es/man1/dpkg-query.1.gz \
	./usr/share/man/pl/man8/dpkg-statoverride.8.gz \
	./usr/share/locale/sv/ \
	./usr/share/man/man5/ \
	./usr/share/man/ja/man1/ \
	./usr/share/doc/dpkg/THANKS.gz \
	./usr/share/locale/gl/LC_MESSAGES/dpkg.mo \
	./usr/share/man/es/man1/dpkg-maintscript-helper.1.gz \
	./usr/share/man/hu/man5/dpkg.cfg.5.gz \
	./usr/share/locale/pa/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/nl/ \
	./usr/share/dpkg/ \
	./usr/share/man/fr/man5/ \
	./usr/share/man/it/man1/dpkg-deb.1.gz \
	./usr/share/man/de/man5/dpkg.cfg.5.gz \
	./usr/share/man/fr/man1/dpkg-maintscript-helper.1.gz \
	./etc/logrotate.d/dpkg \
	./usr/share/locale/el/LC_MESSAGES/dpkg.mo \
	./usr/share/man/pl/man1/dpkg-query.1.gz \
	./usr/share/locale/id/ \
	./usr/share/locale/ast/ \
	./usr/share/man/fr/man1/ \
	./usr/share/locale/ca/LC_MESSAGES/ \
	./usr/share/man/sv/man8/start-stop-daemon.8.gz \
	./usr/share/man/hu/man5/ \
	./usr/share/locale/es/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/bs/ \
	./usr/share/man/fr/man1/dpkg.1.gz \
	./usr/share/locale/tl/ \
	./usr/share/man/it/man1/dpkg-split.1.gz \
	./usr/share/locale/ro/LC_MESSAGES/ \
	./usr/share/man/ja/man1/dpkg-trigger.1.gz \
	./usr/share/dpkg/ostable \
	./usr/share/man/pl/man8/ \
	./usr/share/locale/vi/ \
	./usr/share/man/pl/man1/dpkg-trigger.1.gz \
	./usr/share/locale/eo/ \
	./usr/share/locale/th/LC_MESSAGES/ \
	./usr/share/man/fr/man8/update-alternatives.8.gz \
	./usr/share/locale/nb/LC_MESSAGES/ \
	./usr/share/locale/dz/ \
	./usr/share/locale/pt_BR/ \
	./usr/share/locale/zh_CN/LC_MESSAGES/dpkg.mo \
	./usr/share/man/man8/update-alternatives.8.gz \
	./usr/share/locale/dz/LC_MESSAGES/ \
	./usr/share/man/es/man8/update-alternatives.8.gz \
	./var/lib/dpkg/info/ \
	./usr/bin/dpkg-deb \
	./usr/share/locale/fr/ \
	./usr/share/locale/bs/LC_MESSAGES/dpkg.mo \
	./usr/share/lintian/overrides/ \
	./usr/share/locale/ne/LC_MESSAGES/dpkg.mo \
	./usr/share/man/es/man8/start-stop-daemon.8.gz \
	./usr/share/man/fr/man1/dpkg-deb.1.gz \
	./usr/share/doc/dpkg/changelog.gz \
	./usr/share/man/fr/man8/start-stop-daemon.8.gz \
	./usr/share/man/it/man5/dpkg.cfg.5.gz \
	./usr/share/man/de/man1/dpkg-maintscript-helper.1.gz \
	./usr/share/locale/cs/ \
	./usr/share/man/de/man5/ \
	./usr/share/man/it/man1/ \
	./usr/share/locale/pt/ \
	./usr/share/locale/fr/LC_MESSAGES/ \
	./usr/share/locale/gl/LC_MESSAGES/ \
	./etc/alternatives/README \
	./usr/share/man/fr/man8/ \
	./usr/share/man/man1/ \
	./usr/share/man/es/man8/dpkg-statoverride.8.gz \
	./usr/share/man/ja/man8/dpkg-divert.8.gz \
	./usr/share/man/sv/man8/update-alternatives.8.gz \
	./usr/share/man/pl/man8/update-alternatives.8.gz \
	./etc/cron.daily/dpkg \
	./usr/share/man/man8/dpkg-statoverride.8.gz \
	./usr/share/doc/dpkg/AUTHORS \
	./usr/share/man/ja/man1/dpkg-maintscript-helper.1.gz \
	./usr/share/locale/zh_TW/LC_MESSAGES/ \
	./usr/share/locale/zh_CN/ \
	./usr/share/man/pl/man8/start-stop-daemon.8.gz \
	./usr/share/locale/el/ \
	./etc/dpkg/ \
	./usr/share/man/hu/ \
	./usr/share/man/es/man5/dpkg.cfg.5.gz \
	./usr/share/man/de/man1/dpkg-trigger.1.gz \
	./usr/share/locale/vi/LC_MESSAGES/ \
	./usr/share/ \
	./usr/share/locale/ko/LC_MESSAGES/ \
	./usr/share/locale/ku/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/nb/ \
	./usr/share/locale/dz/LC_MESSAGES/dpkg.mo \
	./usr/share/man/ja/man8/start-stop-daemon.8.gz \
	./usr/ \
	./usr/share/locale/pt/LC_MESSAGES/ \
	./usr/share/locale/eu/LC_MESSAGES/ \
	./usr/share/locale/pt/LC_MESSAGES/dpkg.mo \
	./etc/cron.daily/ \
	./usr/share/locale/pl/ \
	./usr/share/man/de/man8/update-alternatives.8.gz \
	./usr/share/man/de/man1/ \
	./usr/share/man/es/man1/dpkg.1.gz \
	./usr/share/locale/ca/ \
	./etc/alternatives/ \
	./usr/share/locale/ro/ \
	./usr/sbin/ \
	./usr/share/locale/de/LC_MESSAGES/ \
	./usr/share/locale/mr/ \
	./usr/share/locale/fr/LC_MESSAGES/dpkg.mo \
	./usr/share/man/pl/man1/dpkg-deb.1.gz \
	./usr/share/locale/tl/LC_MESSAGES/dpkg.mo \
	./usr/share/man/man1/dpkg-trigger.1.gz \
	./usr/share/man/it/ \
	./usr/share/locale/id/LC_MESSAGES/ \
	./usr/share/locale/et/ \
	./usr/share/locale/ast/LC_MESSAGES/ \
	./usr/share/man/it/man1/dpkg-query.1.gz \
	./usr/share/locale/sk/LC_MESSAGES/dpkg.mo \
	./usr/share/doc/dpkg/changelog.Debian.gz \
	./usr/share/locale/pt_BR/LC_MESSAGES/dpkg.mo \
	./usr/share/dpkg/triplettable \
	./usr/share/locale/es/LC_MESSAGES/ \
	./usr/share/locale/nl/LC_MESSAGES/ \
	./usr/share/man/ja/man8/ \
	./usr/share/locale/zh_TW/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/bs/LC_MESSAGES/ \
	./usr/share/man/de/man8/start-stop-daemon.8.gz \
	./usr/share/man/sv/man5/ \
	./usr/sbin/install-info \
	./usr/share/man/sv/man8/ \
	./usr/share/man/it/man8/start-stop-daemon.8.gz \
	./usr/share/man/ja/man1/dpkg-deb.1.gz \
	./usr/share/dpkg/cputable \
	./usr/share/locale/ca/LC_MESSAGES/dpkg.mo \
	./usr/share/man/pl/man1/dpkg.1.gz \
	./usr/share/man/pl/man1/ \
	./usr/share/locale/lt/LC_MESSAGES/ \
	./usr/share/man/man8/dpkg-divert.8.gz \
	./usr/share/man/es/man8/dpkg-divert.8.gz \
	./usr/share/locale/da/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/et/LC_MESSAGES/dpkg.mo \
	./usr/share/man/ja/man8/update-alternatives.8.gz \
	./usr/share/man/sv/man1/ \
	./var/lib/ \
	./usr/share/man/de/ \
	./usr/share/locale/ja/ \
	./usr/share/man/it/man5/ \
	./usr/share/locale/eu/ \
	./usr/share/dpkg/archtable \
	./usr/share/locale/gl/ \
	./usr/share/locale/pa/ \
	./var/ \
	./var/lib/dpkg/alternatives/ \
	./usr/share/locale/zh_CN/LC_MESSAGES/ \
	./usr/share/locale/zh_TW/ \
	./usr/share/doc/dpkg/README.feature-removal-schedule.gz \
	./usr/bin/update-alternatives \
	./usr/share/locale/vi/LC_MESSAGES/dpkg.mo \
	./usr/share/man/de/man8/dpkg-statoverride.8.gz \
	./usr/share/man/sv/man8/dpkg-divert.8.gz \
	./usr/share/locale/th/LC_MESSAGES/dpkg.mo \
	./usr/share/man/de/man1/dpkg-query.1.gz \
	./sbin/start-stop-daemon \
	./usr/share/man/es/ \
	./usr/bin/dpkg-divert \
	./usr/share/man/es/man5/ \
	./usr/share/locale/et/LC_MESSAGES/ \
	./ \
	./usr/share/man/fr/man8/dpkg-statoverride.8.gz \
	./usr/share/man/sv/man8/dpkg-statoverride.8.gz \
	./usr/share/locale/hu/ \
	./usr/share/locale/el/LC_MESSAGES/ \
	./usr/share/man/sv/man1/dpkg-maintscript-helper.1.gz \
	./usr/share/locale/sk/ \
	./usr/share/locale/it/LC_MESSAGES/dpkg.mo \
	./usr/sbin/dpkg-statoverride \
	./usr/share/doc/dpkg/usertags.gz \
	./usr/share/man/es/man1/dpkg-trigger.1.gz \
	./usr/share/locale/lt/ \
	./usr/share/man/es/man1/ \
	./usr/share/man/sv/man1/dpkg-split.1.gz \
	./usr/share/locale/pl/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/th/ \
	./usr/share/man/it/man8/ \
	./usr/share/man/ja/ \
	./usr/share/man/man1/dpkg-deb.1.gz \
	./usr/share/locale/ \
	./usr/share/locale/pt_BR/LC_MESSAGES/ \
	./usr/share/locale/eu/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/km/LC_MESSAGES/ \
	./usr/share/locale/nb/LC_MESSAGES/dpkg.mo \
	./usr/share/man/de/man8/ \
	./usr/share/man/es/man8/ \
	./usr/share/man/ja/man1/dpkg-query.1.gz \
	./usr/share/man/pl/man1/dpkg-split.1.gz \
	./usr/share/man/fr/ \
	./usr/share/locale/km/ \
	./usr/share/man/sv/ \
	./usr/share/locale/ru/ \
	./usr/share/lintian/ \
	./usr/share/locale/nn/LC_MESSAGES/ \
	./var/lib/dpkg/parts/ \
	./usr/share/man/man1/dpkg.1.gz \
	./usr/share/man/man1/dpkg-maintscript-helper.1.gz \
	./usr/share/man/man8/ \
	./usr/share/man/de/man1/dpkg-deb.1.gz \
	./usr/share/man/ja/man1/dpkg.1.gz \
	./usr/share/locale/ast/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/cs/LC_MESSAGES/ \
	./usr/share/locale/ja/LC_MESSAGES/dpkg.mo \
	./usr/bin/dpkg-split \
	./usr/share/man/fr/man1/dpkg-query.1.gz \
	./usr/share/locale/sv/LC_MESSAGES/ \
	./usr/share/locale/eo/LC_MESSAGES/ \
	./var/lib/dpkg/updates/ \
	./usr/bin/dpkg-statoverride \
	./usr/share/man/de/man1/dpkg.1.gz \
	./usr/share/locale/nn/LC_MESSAGES/dpkg.mo \
	./usr/share/man/es/man1/dpkg-deb.1.gz \
	./usr/share/locale/cs/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/es/ \
	./usr/share/man/pl/man8/dpkg-divert.8.gz \
	./etc/dpkg/dpkg.cfg \
	./usr/share/man/it/man1/dpkg.1.gz \
	./usr/bin/dpkg \
	./etc/logrotate.d/ \
	./sbin/ \
	./etc/dpkg/dpkg.cfg.d/ \
	./usr/share/man/ja/man8/dpkg-statoverride.8.gz \
	./usr/share/locale/ku/ \
	./usr/share/man/es/man1/dpkg-split.1.gz \
	./usr/share/locale/mr/LC_MESSAGES/dpkg.mo \
	./usr/share/man/sv/man1/dpkg-deb.1.gz \
	./usr/share/doc/dpkg/ \
	./usr/share/locale/it/LC_MESSAGES/ \
	./var/lib/dpkg/ \
	./usr/share/locale/da/LC_MESSAGES/ \
	./usr/share/dpkg/abitable \
	./usr/share/man/sv/man1/dpkg-query.1.gz \
	./usr/share/man/de/man1/dpkg-split.1.gz \
	./usr/share/locale/nn/ \
	./usr/share/man/fr/man8/dpkg-divert.8.gz \
	./usr/share/man/fr/man1/dpkg-trigger.1.gz \
	./usr/share/locale/da/ \
	./etc/ \
	./usr/share/man/sv/man1/dpkg-trigger.1.gz \
	./usr/share/locale/pa/LC_MESSAGES/ \
	./usr/share/locale/id/LC_MESSAGES/dpkg.mo \
	./usr/share/man/pl/ \
	./usr/share/locale/de/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/nl/LC_MESSAGES/dpkg.mo \
	./usr/share/man/pl/man1/dpkg-maintscript-helper.1.gz \
	./usr/share/locale/ro/LC_MESSAGES/dpkg.mo \
	./usr/bin/ \
	./usr/share/man/fr/man1/dpkg-split.1.gz \
	./usr/share/man/man5/dpkg.cfg.5.gz \
	./usr/share/locale/mr/LC_MESSAGES/ \
	./usr/share/locale/ko/ \
	./usr/share/locale/sv/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/de/ \
	./usr/share/man/man1/dpkg-query.1.gz \
	./usr/share/man/ja/man5/dpkg.cfg.5.gz \
	./usr/share/man/ja/man5/ \
	./usr/sbin/update-alternatives \
	./usr/share/lintian/overrides/dpkg \
	./usr/share/locale/hu/LC_MESSAGES/dpkg.mo \
	./usr/share/man/sv/man5/dpkg.cfg.5.gz \
	./usr/share/man/fr/man5/dpkg.cfg.5.gz \
	./usr/share/man/pl/man5/ \
	./usr/share/locale/ne/ \
	./usr/share/man/it/man8/dpkg-statoverride.8.gz \
	./usr/bin/dpkg-query \
	./usr/share/doc/ \
	./usr/share/man/it/man8/update-alternatives.8.gz \
	./usr/share/doc/dpkg/copyright \
	./usr/share/man/de/man8/dpkg-divert.8.gz \
	./usr/share/man/ \
	./usr/share/locale/sk/LC_MESSAGES/ \
	./usr/share/locale/pl/LC_MESSAGES/ \
	./usr/share/locale/ko/LC_MESSAGES/dpkg.mo \
	./usr/share/locale/ne/LC_MESSAGES/\
"
#FAKE LICENSE FOR TESTING!!!
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta/COPYING.MIT;md5=3da9cfbcb788c80a0384361b4de20420"
