PACKAGES = "libicu-dev libicu48"
PROVIDES = "libicu-dev libicu48"
SRC_URI = " \
	http://archive.raspbian.org/raspbian/pool/main/i/icu/libicu-dev_4.8.1.1-12+deb7u3_armhf.deb;unpack=0;name=deb0\
	http://archive.raspbian.org/raspbian/pool/main/i/icu/libicu48_4.8.1.1-12+deb7u3_armhf.deb;unpack=0;name=deb1\
"
DEBFILENAME_libicu-dev = "libicu-dev_4.8.1.1-12+deb7u3_armhf.deb"
SRC_URI[deb0.sha256sum] = "33939826aca393cd50d830e00c20d5cda87fd2d360d35094dbfabd92f7935947"
SRC_URI[deb0.md5sum] = "f226b58a0e6b5d896eec73a3826a2bc3"
DEBFILENAME_libicu48 = "libicu48_4.8.1.1-12+deb7u3_armhf.deb"
SRC_URI[deb1.sha256sum] = "5a66bf1baa7d065914f13718b6b4a1ef0bf7d0e5c67a1628997371cfa340a02f"
SRC_URI[deb1.md5sum] = "8854ea27c2d513b9bffa626e73773c16"

RDEPENDS_lib${PN}-dev = "libc6 (>= 2.13-28) libgcc1 (>= 1:4.4.0) libicu48 (= 4.8.1.1-12+deb7u3) libstdc++6 (>= 4.3.0) libc6-dev"
RDEPENDS_lib${PN}48 = "libc6 (>= 2.13-28) libgcc1 (>= 1:4.4.0) libstdc++6 (>= 4.4.0)"
DEPENDS = "libgcc1 libc6-dev libstdc++6 libc6"


inherit deb_group

# Prebuilt binaries, no need for any default dependencies
INHIBIT_DEFAULT_DEPS = "1"
INHIBIT_PACKAGE_STRIP = "1"
INSANE_SKIP_${PN} += "already-stripped"

FILES_libicu-dev = " \
	./usr/include/unicode/uobject.h \
	./usr/lib/arm-linux-gnueabihf/libicui18n.a \
	./usr/include/unicode/stsearch.h \
	./usr/sbin/icupkg \
	./usr/share/doc/libicu-dev/examples/uresb/ \
	./usr/lib/arm-linux-gnueabihf/icu/4.8.1.1/Makefile.inc \
	./usr/share/doc/libicu-dev/examples/uciter8/Makefile \
	./usr/share/man/man1/icu-config.1.gz \
	./usr/share/doc/libicu-dev/examples/ufortune/ufortune.c \
	./usr/share/doc/libicu-dev/changelog.Debian.gz \
	./usr/share/doc/libicu-dev/examples/msgfmt/main.cpp \
	./usr/include/unicode/udata.h \
	./usr/include/unicode/dtrule.h \
	./usr/share/doc/libicu-dev/examples/layout/arraymem.h \
	./usr/share/doc/libicu-dev/examples/ufortune/ufortune.vcxproj.filters \
	./usr/include/unicode/urename.h \
	./usr/include/unicode/datefmt.h \
	./usr/share/doc/libicu-dev/examples/datefmt/answers/main_2.cpp \
	./usr/include/unicode/std_string.h \
	./usr/include/unicode/uchriter.h \
	./usr/share/doc/libicu-dev/examples/uresb/uresb.c \
	./usr/share/doc/libicu-dev/examples/layout/UnicodeReader.cpp \
	./usr/include/unicode/uconfig.h \
	./usr/share/doc/libicu-dev/examples/case/readme.txt \
	./usr/share/doc/libicu-dev/examples/ustring/ustring.sln \
	./usr/share/doc/libicu-dev/examples/translit/answers/main_2.cpp \
	./usr/bin/icu-config \
	./usr/share/doc/libicu-dev/examples/translit/util.cpp \
	./usr/include/unicode/locid.h \
	./usr/include/unicode/utrans.h \
	./usr/include/unicode/coleitr.h \
	./usr/include/unicode/dtitvinf.h \
	./usr/include/unicode/fmtable.h \
	./usr/include/unicode/unistr.h \
	./usr/include/unicode/utf32.h \
	./usr/include/unicode/ustdio.h \
	./usr/include/unicode/utf16.h \
	./usr/share/doc/libicu-dev/examples/case/case.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/msgfmt/msgfmt.vcxproj \
	./usr/share/doc/libicu-dev/examples/case/Makefile \
	./usr/lib/arm-linux-gnueabihf/icu/ \
	./usr/lib/arm-linux-gnueabihf/libicule.so \
	./usr/lib/arm-linux-gnueabihf/libicui18n.so \
	./usr/include/ \
	./usr/include/unicode/unorm2.h \
	./usr/include/layout/ParagraphLayout.h \
	./usr/lib/arm-linux-gnueabihf/libicule.a \
	./usr/share/icu/4.8.1.1/mkinstalldirs \
	./usr/share/doc/libicu-dev/examples/date/date.vcxproj.filters \
	./usr/bin/pkgdata \
	./usr/include/unicode/timezone.h \
	./usr/share/doc/libicu-dev/examples/translit/answers/unaccent.h \
	./usr/share/icu/ \
	./usr/include/unicode/localpointer.h \
	./usr/share/doc/libicu-dev/examples/cal/ \
	./usr/share/doc/libicu-dev/examples/all/all.sln \
	./usr/include/unicode/normlzr.h \
	./usr/share/icu/4.8.1.1/config/mh-linux \
	./usr/include/unicode/unimatch.h \
	./usr/include/unicode/gregocal.h \
	./usr/include/unicode/measfmt.h \
	./usr/lib/arm-linux-gnueabihf/libicuuc.so \
	./usr/share/doc/libicu-dev/examples/legacy/oldcol.cpp \
	./usr/share/man/man1/gencfu.1.gz \
	./usr/include/unicode/ushape.h \
	./usr/lib/arm-linux-gnueabihf/icu/pkgdata.inc \
	./usr/share/doc/libicu-dev/examples/ufortune/ \
	./usr/include/layout/loengine.h \
	./usr/lib/arm-linux-gnueabihf/pkgconfig/icu-lx.pc \
	./usr/share/man/man1/genbrk.1.gz \
	./usr/share/doc/libicu-dev/examples/uresb/uresb.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/layout/Sample.txt \
	./usr/share/doc/libicu-dev/examples/ucnv/Makefile \
	./usr/include/layout/LESwaps.h \
	./usr/share/doc/libicu-dev/examples/date/date.c \
	./usr/share/doc/libicu-dev/examples/ufortune/resources/fortune_resources.mak \
	./usr/share/doc/libicu-dev/examples/cal/cal.vcxproj \
	./usr/share/icu/4.8.1.1/install-sh \
	./usr/share/doc/libicu-dev/examples/Makefile \
	./usr/share/doc/libicu-dev/examples/ugrep/ugrep.vcxproj \
	./usr/include/unicode/measure.h \
	./usr/share/doc/libicu-dev/examples/layout/ucreader.h \
	./usr/share/doc/libicu-dev/examples/numfmt/main.cpp \
	./usr/share/doc/libicu-dev/examples/ustring/Makefile \
	./usr/share/doc/libicu-dev/examples/numfmt/ \
	./usr/share/doc/libicu-dev/examples/ugrep/ugrep.sln \
	./usr/lib/arm-linux-gnueabihf/libicutu.a \
	./usr/share/doc/libicu-dev/examples/uresb/resources.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/layout/readme.html \
	./usr/include/unicode/uiter.h \
	./usr/share/doc/libicu-dev/examples/props/Makefile \
	./usr/bin/uconv \
	./usr/share/doc/libicu-dev/copyright \
	./usr/share/doc/libicu-dev/examples/datefmt/util.h \
	./usr/share/doc/libicu-dev/examples/datefmt/util.cpp \
	./usr/share/doc/libicu-dev/examples/case/ \
	./usr/include/unicode/stringpiece.h \
	./usr/share/doc/libicu-dev/examples/coll/Makefile \
	./usr/include/unicode/pwin32.h \
	./usr/share/doc/libicu-dev/examples/ufortune/Makefile \
	./usr/include/unicode/alphaindex.h \
	./usr/share/doc/libicu-dev/examples/date/ \
	./usr/share/doc/libicu-dev/examples/uciter8/readme.txt \
	./usr/share/doc/libicu-dev/examples/layout/LayoutSample.rc \
	./usr/include/unicode/utf.h \
	./usr/share/doc/libicu-dev/examples/ucnv/convsamp.cpp \
	./usr/include/unicode/locdspnm.h \
	./usr/share/icu/4.8.1.1/ \
	./usr/include/unicode/plurrule.h \
	./usr/include/unicode/tztrans.h \
	./usr/share/doc/libicu-dev/examples/strsrch/strsrch.sln \
	./usr/share/doc/libicu-dev/ \
	./usr/include/unicode/currpinf.h \
	./usr/share/doc/libicu-dev/examples/layout/GnomeGUISupport.h \
	./usr/share/doc/libicu-dev/examples/layout/ScriptCompositeFontInstance.h \
	./usr/bin/makeconv \
	./usr/bin/ \
	./usr/share/doc/libicu-dev/examples/msgfmt/answers/main_1.cpp \
	./usr/include/unicode/udatpg.h \
	./usr/share/doc/libicu-dev/examples/translit/ \
	./usr/lib/arm-linux-gnueabihf/pkgconfig/icu-i18n.pc \
	./usr/include/unicode/dtptngen.h \
	./usr/share/doc/libicu-dev/examples/uciter8/uciter8.vcxproj.filters \
	./usr/include/unicode/msgfmt.h \
	./usr/include/unicode/udateintervalformat.h \
	./usr/include/unicode/curramt.h \
	./usr/lib/arm-linux-gnueabihf/pkgconfig/icu-io.pc \
	./usr/include/unicode/ures.h \
	./usr/share/doc/libicu-dev/examples/uresb/resources.mak \
	./usr/lib/arm-linux-gnueabihf/libicuio.so \
	./usr/share/doc/libicu-dev/examples/case/case.vcxproj \
	./usr/lib/ \
	./usr/share/doc/libicu-dev/examples/msgfmt/answers/main_2.cpp \
	./usr/sbin/genccode \
	./usr/share/doc/libicu-dev/examples/udata/reader.c \
	./usr/lib/arm-linux-gnueabihf/libiculx.so \
	./usr/share/man/man1/genctd.1.gz \
	./usr/share/doc/libicu-dev/examples/break/readme.txt \
	./usr/include/unicode/strenum.h \
	./usr/share/doc/libicu-dev/examples/date/Makefile \
	./usr/share/doc/libicu-dev/examples/numfmt/util.h \
	./usr/share/doc/libicu-dev/examples/ugrep/ugrep.cpp \
	./usr/share/doc/libicu-dev/examples/coll/readme.txt \
	./usr/include/unicode/coll.h \
	./usr/share/doc/libicu-dev/examples/legacy/legacy.vcxproj \
	./usr/lib/arm-linux-gnueabihf/libicudata.a \
	./usr/share/doc/libicu-dev/examples/layout/GDIFontMap.h \
	./usr/share/doc/libicu-dev/examples/translit/translit.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/translit/main.cpp \
	./usr/share/doc/libicu-dev/examples/coll/coll.vcxproj \
	./usr/share/doc/libicu-dev/examples/translit/util.h \
	./usr/share/doc/libicu-dev/examples/numfmt/numfmt.vcxproj \
	./usr/include/unicode/rep.h \
	./usr/include/unicode/uloc.h \
	./usr/share/doc/libicu-dev/examples/layout/gnomeglue.h \
	./usr/include/unicode/upluralrules.h \
	./usr/share/doc/libicu-dev/examples/numfmt/util.cpp \
	./usr/share/doc/libicu-dev/examples/layout/Surface.h \
	./usr/include/unicode/symtable.h \
	./usr/lib/arm-linux-gnueabihf/ \
	./usr/share/doc/libicu-dev/examples/layout/sfnt.h \
	./usr/share/doc/libicu-dev/examples/strsrch/readme.txt \
	./usr/include/unicode/ucnv.h \
	./usr/include/unicode/basictz.h \
	./usr/include/unicode/plurfmt.h \
	./usr/share/doc/libicu-dev/examples/msgfmt/answers/main_3.cpp \
	./usr/include/unicode/bmsearch.h \
	./usr/include/unicode/udeprctd.h \
	./usr/sbin/gennorm2 \
	./usr/share/doc/libicu-dev/examples/translit/unaccent.cpp \
	./usr/share/doc/libicu-dev/examples/layout/gdiglue.cpp \
	./usr/include/unicode/ \
	./usr/include/unicode/measunit.h \
	./usr/share/doc/libicu-dev/examples/props/ \
	./usr/include/unicode/icudataver.h \
	./usr/share/doc/libicu-dev/examples/break/ \
	./usr/bin/gencnval \
	./usr/share/man/man8/gensprep.8.gz \
	./usr/share/doc/libicu-dev/examples/layout/GDIFontMap.cpp \
	./usr/share/icu/4.8.1.1/config/ \
	./usr/include/unicode/uset.h \
	./usr/share/doc/libicu-dev/examples/msgfmt/util.h \
	./usr/share/doc/libicu-dev/examples/props/props.vcxproj \
	./usr/include/unicode/ucharstriebuilder.h \
	./usr/share/doc/libicu-dev/examples/ufortune/fortunedefs.mk \
	./usr/share/doc/libicu-dev/examples/uresb/readme.txt \
	./usr/share/man/man1/ \
	./usr/share/doc/libicu-dev/examples/datefmt/datefmt.sln \
	./usr/share/man/man1/uconv.1.gz \
	./usr/share/doc/libicu-dev/examples/strsrch/ \
	./usr/share/man/man1/pkgdata.1.gz \
	./usr/include/unicode/usystem.h \
	./usr/include/unicode/currunit.h \
	./usr/include/unicode/unifilt.h \
	./usr/share/doc/libicu-dev/examples/layout/FontMap.Gnome \
	./usr/share/doc/libicu-dev/NEWS.Debian.gz \
	./usr/share/doc/libicu-dev/examples/layout/clayout.c \
	./usr/include/unicode/usprep.h \
	./usr/share/doc/libicu-dev/examples/datefmt/Makefile \
	./usr/share/doc/libicu-dev/examples/datecal/Makefile \
	./usr/include/unicode/putil.h \
	./usr/share/doc/libicu-dev/examples/cal/Makefile \
	./usr/include/unicode/ucnvsel.h \
	./usr/share/doc/libicu-dev/examples/layout/ucreader.cpp \
	./usr/share/doc/libicu-dev/examples/numfmt/numfmt.sln \
	./usr/share/doc/libicu-dev/examples/layout/FontTableCache.cpp \
	./usr/lib/arm-linux-gnueabihf/libiculx.a \
	./usr/include/unicode/dtitvfmt.h \
	./usr/share/doc/libicu-dev/examples/udata/Makefile \
	./usr/share/doc/libicu-dev/examples/uresb/uresb.vcxproj \
	./usr/share/man/man8/ \
	./usr/share/doc/libicu-dev/examples/udata/udata.sln \
	./usr/share/doc/libicu-dev/examples/layout/GUISupport.h \
	./usr/share/doc/libicu-dev/examples/msgfmt/msgfmt.sln \
	./usr/share/doc/libicu-dev/examples/citer/citer.vcxproj \
	./usr/include/unicode/uchar.h \
	./usr/share/doc/libicu-dev/examples/ \
	./usr/include/unicode/unifunct.h \
	./usr/share/doc/libicu-dev/examples/ucnv/data02.bin \
	./usr/share/doc/libicu-dev/examples/ucnv/ucnv.sln \
	./usr/share/doc/libicu-dev/examples/ugrep/ \
	./usr/include/unicode/tzrule.h \
	./usr/include/unicode/bytestream.h \
	./usr/share/doc/libicu-dev/examples/layout/RenderingSurface.h \
	./usr/share/doc/libicu-dev/examples/layout/ScriptCompositeFontInstance.cpp \
	./usr/include/unicode/fieldpos.h \
	./usr/include/unicode/stringtriebuilder.h \
	./usr/bin/genctd \
	./usr/include/layout/LEInsertionList.h \
	./usr/include/unicode/vtzone.h \
	./usr/include/unicode/udraft.h \
	./usr/share/doc/libicu-dev/examples/layout/cgnomelayout.c \
	./usr/include/unicode/regex.h \
	./usr/share/doc/libicu-dev/examples/layout/pflow.c \
	./usr/share/doc/libicu-dev/examples/layout/paragraph.cpp \
	./usr/include/unicode/ulocdata.h \
	./usr/share/doc/libicu-dev/examples/csdet/Makefile \
	./usr/share/doc/libicu-dev/examples/layout/pflow.h \
	./usr/include/unicode/idna.h \
	./usr/include/unicode/ustringtrie.h \
	./usr/include/unicode/caniter.h \
	./usr/include/unicode/docmain.h \
	./usr/include/layout/playout.h \
	./usr/share/doc/libicu-dev/examples/msgfmt/msgfmt.vcxproj.filters \
	./usr/include/unicode/messagepattern.h \
	./usr/include/unicode/uidna.h \
	./usr/share/doc/libicu-dev/examples/case/ucase.c \
	./usr/share/doc/libicu-dev/examples/layout/layout.vcxproj \
	./usr/share/doc/libicu-dev/examples/ucnv/data01.txt \
	./usr/share/doc/libicu-dev/examples/break/Makefile \
	./usr/include/layout/LETableReference.h \
	./usr/include/unicode/ucsdet.h \
	./usr/ \
	./usr/share/doc/libicu-dev/examples/layout/GnomeFontMap.cpp \
	./usr/lib/arm-linux-gnueabihf/libicuio.a \
	./usr/share/doc/libicu-dev/examples/legacy/newcol.cpp \
	./usr/share/doc/libicu-dev/examples/datefmt/answers/main_3.cpp \
	./usr/share/doc/libicu-dev/examples/date/date.vcxproj \
	./usr/share/doc/libicu-dev/examples/coll/coll.vcxproj.filters \
	./usr/include/unicode/icuplug.h \
	./usr/include/unicode/selfmt.h \
	./usr/share/icu/4.8.1.1/license.html \
	./usr/lib/arm-linux-gnueabihf/libicuuc.a \
	./usr/include/unicode/translit.h \
	./usr/include/unicode/bytestriebuilder.h \
	./usr/share/doc/libicu-dev/examples/datefmt/answers/ \
	./usr/share/doc/libicu-dev/examples/udata/writer.c \
	./usr/include/unicode/decimfmt.h \
	./usr/include/unicode/umisc.h \
	./usr/include/unicode/choicfmt.h \
	./usr/share/doc/libicu-dev/examples/datefmt/README.TXT \
	./usr/include/unicode/dtfmtsym.h \
	./usr/include/unicode/tmutamt.h \
	./usr/include/unicode/bytestrie.h \
	./usr/include/unicode/rbtz.h \
	./usr/share/doc/libicu-dev/examples/numfmt/numfmt.vcxproj.filters \
	./usr/include/unicode/utf_old.h \
	./usr/include/unicode/uregex.h \
	./usr/bin/gencfu \
	./usr/share/doc/libicu-dev/examples/citer/readme.txt \
	./usr/share/doc/libicu-dev/examples/udata/writer.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/ufortune/resources/es.txt \
	./usr/share/doc/libicu-dev/examples/layout/paragraph.h \
	./usr/share/doc/libicu-dev/examples/layout/GDIGUISupport.cpp \
	./usr/share/doc/libicu-dev/examples/translit/translit.vcxproj \
	./usr/share/doc/libicu-dev/examples/case/case.sln \
	./usr/share/doc/libicu-dev/examples/ugrep/readme.txt \
	./usr/include/unicode/rbbi.h \
	./usr/share/doc/libicu-dev/examples/udata/reader.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/date/readme.txt \
	./usr/include/unicode/errorcode.h \
	./usr/share/doc/libicu-dev/examples/layout/layout.sln \
	./usr/share/man/man1/derb.1.gz \
	./usr/share/doc/libicu-dev/examples/ufortune/resources/res-file-list.txt \
	./usr/include/unicode/dbbi.h \
	./usr/share/doc/libicu-dev/examples/translit/answers/ \
	./usr/share/doc/libicu-dev/examples/layout/Surface.cpp \
	./usr/include/unicode/parsepos.h \
	./usr/include/unicode/urep.h \
	./usr/share/doc/libicu-dev/examples/ugrep/ugrep.vcxproj.filters \
	./usr/lib/arm-linux-gnueabihf/pkgconfig/icu-le.pc \
	./usr/include/unicode/appendable.h \
	./usr/share/man/man1/makeconv.1.gz \
	./usr/include/layout/plruns.h \
	./usr/share/doc/libicu-dev/examples/uresb/sr.txt \
	./usr/include/layout/LEScripts.h \
	./usr/share/doc/libicu-dev/examples/ucnv/readme.txt \
	./usr/share/doc/libicu-dev/examples/defs.mk \
	./usr/include/unicode/resbund.h \
	./usr/lib/arm-linux-gnueabihf/icu/4.8.1.1/ \
	./usr/sbin/ \
	./usr/include/layout/LEGlyphFilter.h \
	./usr/share/doc/libicu-dev/examples/layout/GDIFontInstance.cpp \
	./usr/share/doc/libicu-dev/examples/legacy/ \
	./usr/share/doc/libicu-dev/examples/csdet/csdet.vcxproj.filters \
	./usr/include/unicode/dtintrv.h \
	./usr/include/unicode/numsys.h \
	./usr/bin/icuinfo \
	./usr/share/doc/libicu-dev/examples/break/break.cpp \
	./usr/include/unicode/utypes.h \
	./usr/lib/arm-linux-gnueabihf/icu/current \
	./usr/include/unicode/uvernum.h \
	./usr/share/doc/libicu-dev/examples/layout/FontTableCache.h \
	./usr/share/doc/libicu-dev/examples/cal/cal.sln \
	./usr/include/unicode/ucoleitr.h \
	./usr/share/doc/libicu-dev/examples/cal/Makefile.in \
	./usr/share/doc/libicu-dev/examples/datefmt/main.cpp \
	./usr/share/doc/libicu-dev/examples/strsrch/strsrch.vcxproj.filters \
	./usr/include/unicode/uspoof.h \
	./usr/share/doc/libicu-dev/examples/legacy/legacy.cpp \
	./usr/include/unicode/ubidi.h \
	./usr/share/doc/libicu-dev/examples/uresb/en.txt \
	./usr/share/doc/libicu-dev/examples/csdet/csdet.vcxproj \
	./usr/share/doc/libicu-dev/examples/ufortune/resources/Makefile \
	./usr/include/unicode/utmscale.h \
	./usr/share/doc/libicu-dev/examples/cal/readme.txt \
	./usr/include/unicode/uenum.h \
	./usr/share/doc/libicu-dev/examples/numfmt/Makefile \
	./usr/lib/arm-linux-gnueabihf/pkgconfig/icu-uc.pc \
	./usr/share/doc/libicu-dev/examples/datefmt/answers/main_1.cpp \
	./usr/share/doc/libicu-dev/examples/layout/FontMap.GDI \
	./usr/share/man/man8/icupkg.8.gz \
	./usr/include/unicode/ucharstrie.h \
	./usr/bin/genrb \
	./usr/include/unicode/ucal.h \
	./usr/share/doc/libicu-dev/examples/datecal/ccal.c \
	./usr/include/unicode/usetiter.h \
	./usr/share/doc/libicu-dev/examples/layout/Makefile.in \
	./usr/lib/arm-linux-gnueabihf/pkgconfig/ \
	./usr/share/doc/libicu-dev/examples/strsrch/strsrch.cpp \
	./usr/include/unicode/usearch.h \
	./usr/share/doc/libicu-dev/examples/uresb/Makefile \
	./usr/share/doc/libicu-dev/examples/msgfmt/README.TXT \
	./usr/share/doc/libicu-dev/examples/udata/reader.vcxproj \
	./usr/include/unicode/ustream.h \
	./usr/share/doc/libicu-dev/examples/translit/Makefile \
	./usr/include/layout/LETypes.h \
	./usr/share/doc/libicu-dev/examples/strsrch/strsrch.vcxproj \
	./usr/share/doc/libicu-dev/examples/datefmt/ \
	./usr/share/doc/libicu-dev/examples/layout/gnomeglue.cpp \
	./usr/include/unicode/uldnames.h \
	./usr/share/doc/libicu-dev/examples/layout/GnomeFontMap.h \
	./usr/share/man/man8/genccode.8.gz \
	./usr/include/unicode/unirepl.h \
	./usr/share/doc/libicu-dev/examples/layout/resource.h \
	./usr/lib/arm-linux-gnueabihf/libicutest.so \
	./usr/share/doc/libicu-dev/examples/layout/layout.cpp \
	./usr/include/unicode/ucat.h \
	./usr/share/doc/libicu-dev/examples/uciter8/uciter8.c \
	./usr/include/unicode/utrace.h \
	./usr/include/layout/LEFontInstance.h \
	./usr/lib/arm-linux-gnueabihf/libicutest.a \
	./usr/bin/genbrk \
	./usr/include/unicode/ucurr.h \
	./usr/include/unicode/ucnv_cb.h \
	./usr/include/unicode/brkiter.h \
	./usr/share/man/man8/gencmn.8.gz \
	./usr/share/doc/libicu-dev/examples/layout/gsupport.h \
	./usr/share/doc/libicu-dev/examples/break/ubreak.c \
	./usr/share/doc/libicu-dev/examples/layout/FontMap.h \
	./usr/share/doc/libicu-dev/examples/break/break.vcxproj \
	./usr/include/unicode/chariter.h \
	./usr/share/doc/libicu-dev/examples/uresb/root.txt \
	./usr/lib/arm-linux-gnueabihf/icu/Makefile.inc \
	./usr/include/unicode/sortkey.h \
	./usr/include/unicode/tmutfmt.h \
	./usr/include/unicode/fpositer.h \
	./usr/include/unicode/normalizer2.h \
	./usr/include/unicode/uintrnal.h \
	./usr/include/unicode/ucnv_err.h \
	./usr/share/doc/libicu-dev/examples/break/break.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/citer/Makefile \
	./usr/include/unicode/ppalmos.h \
	./usr/share/man/ \
	./usr/include/unicode/umsg.h \
	./usr/share/doc/libicu-dev/examples/strsrch/Makefile \
	./usr/share/doc/libicu-dev/examples/csdet/ \
	./usr/include/unicode/colldata.h \
	./usr/include/unicode/umachine.h \
	./usr/share/doc/libicu-dev/examples/props/props.vcxproj.filters \
	./usr/include/unicode/unum.h \
	./usr/share/doc/libicu-dev/examples/ucnv/ucnv.vcxproj \
	./usr/share/man/man1/genrb.1.gz \
	./usr/include/unicode/simpletz.h \
	./usr/include/layout/ \
	./usr/share/doc/libicu-dev/examples/Makefile.in \
	./usr/share/doc/libicu-dev/examples/ustring/ustring.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/ustring/ \
	./usr/share/doc/libicu-dev/examples/translit/answers/main_4.cpp \
	./usr/share/man/man1/icuinfo.1.gz \
	./usr/share/doc/libicu-dev/examples/uresb/uresb.sln \
	./usr/share/doc/libicu-dev/examples/ugrep/Makefile \
	./usr/share/man/man1/gencnval.1.gz \
	./usr/share/doc/libicu-dev/examples/uciter8/uit_len8.c \
	./usr/share/doc/libicu-dev/examples/layout/GnomeFontInstance.h \
	./usr/share/doc/libicu-dev/examples/uciter8/uit_len8.h \
	./usr/share/doc/libicu-dev/examples/date/date.sln \
	./usr/share/doc/libicu-dev/examples/ufortune/ufortune.vcxproj \
	./usr/share/doc/libicu-dev/examples/udata/writer.vcxproj \
	./usr/include/unicode/ubrk.h \
	./usr/sbin/gensprep \
	./usr/share/doc/libicu-dev/examples/layout/rsurface.cpp \
	./usr/include/layout/LEGlyphStorage.h \
	./usr/share/doc/libicu-dev/examples/csdet/csdet.c \
	./usr/share/doc/libicu-dev/examples/all/ \
	./usr/share/doc/libicu-dev/examples/numfmt/readme.txt \
	./usr/share/doc/libicu-dev/examples/layout/Makefile \
	./usr/share/doc/libicu-dev/examples/coll/coll.cpp \
	./usr/share/doc/libicu-dev/examples/ucnv/data06.txt \
	./usr/include/unicode/udat.h \
	./usr/share/doc/libicu-dev/examples/readme.txt \
	./usr/share/doc/libicu-dev/examples/case/case.cpp \
	./usr/share/doc/libicu-dev/examples/cal/uprint.h \
	./usr/share/ \
	./usr/share/doc/libicu-dev/examples/citer/citer.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/cal/uprint.c \
	./usr/include/unicode/uniset.h \
	./usr/share/doc/libicu-dev/examples/layout/UnicodeReader.h \
	./usr/share/doc/libicu-dev/examples/props/props.cpp \
	./usr/include/unicode/uclean.h \
	./usr/include/layout/LELanguages.h \
	./usr/share/doc/libicu-dev/examples/layout/FontMap.cpp \
	./usr/share/doc/libicu-dev/examples/layout/cmaps.cpp \
	./usr/share/doc/libicu-dev/examples/date/uprint.c \
	./usr/share/doc/libicu-dev/examples/legacy/legacy.sln \
	./usr/share/doc/libicu-dev/examples/ufortune/ufortune.sln \
	./usr/share/doc/libicu-dev/examples/date/uprint.h \
	./usr/share/doc/libicu-dev/examples/layout/GDIFontInstance.h \
	./usr/share/doc/libicu-dev/examples/cal/cal.c \
	./usr/include/unicode/ucasemap.h \
	./usr/share/doc/libicu-dev/examples/layout/gnomelayout.cpp \
	./usr/share/doc/libicu-dev/examples/translit/README.TXT \
	./usr/share/doc/libicu-dev/examples/coll/coll.sln \
	./usr/include/unicode/format.h \
	./usr/share/doc/libicu-dev/examples/translit/answers/main_1.cpp \
	./usr/include/unicode/bms.h \
	./usr/share/man/man8/gennorm2.8.gz \
	./usr/share/doc/libicu-dev/examples/date/Makefile.in \
	./usr/lib/arm-linux-gnueabihf/libicudata.so \
	./usr/share/doc/libicu-dev/examples/coll/ \
	./usr/share/doc/libicu-dev/examples/legacy/README \
	./usr/share/doc/libicu-dev/examples/datecal/ \
	./usr/share/doc/libicu-dev/examples/layout/rsurface.h \
	./usr/share/doc/libicu-dev/examples/datecal/cal.cpp \
	./usr/share/doc/libicu-dev/examples/layout/GnomeGUISupport.cpp \
	./usr/share/doc/libicu-dev/examples/numfmt/capi.c \
	./usr/include/unicode/ucol.h \
	./usr/include/unicode/utext.h \
	./usr/include/unicode/ustring.h \
	./usr/share/doc/libicu-dev/examples/datefmt/datefmt.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/ustring/ustring.vcxproj \
	./usr/include/unicode/calendar.h \
	./usr/share/doc/libicu-dev/examples/datefmt/datefmt.vcxproj \
	./ \
	./usr/share/doc/libicu-dev/examples/citer/citer.cpp \
	./usr/share/doc/libicu-dev/examples/msgfmt/Makefile \
	./usr/include/unicode/dcfmtsym.h \
	./usr/share/doc/libicu-dev/examples/ucnv/flagcb.c \
	./usr/share/doc/libicu-dev/examples/csdet/readme.txt \
	./usr/share/doc/libicu-dev/examples/ucnv/flagcb.h \
	./usr/share/doc/libicu-dev/examples/ufortune/resources/ \
	./usr/share/doc/libicu-dev/examples/ucnv/ucnv.vcxproj.filters \
	./usr/share/doc/libicu-dev/examples/uciter8/ \
	./usr/share/doc/libicu-dev/examples/ucnv/ \
	./usr/share/doc/libicu-dev/examples/ustring/readme.txt \
	./usr/share/doc/libicu-dev/examples/break/break.sln \
	./usr/include/unicode/uscript.h \
	./usr/share/doc/libicu-dev/examples/citer/ \
	./usr/share/doc/libicu-dev/examples/layout/cmaps.h \
	./usr/share/doc/libicu-dev/examples/translit/translit.sln \
	./usr/share/doc/libicu-dev/examples/datefmt/answers/main_0.cpp \
	./usr/share/doc/libicu-dev/examples/uciter8/uciter8.sln \
	./usr/share/doc/libicu-dev/examples/translit/unaccent.h \
	./usr/share/doc/libicu-dev/examples/layout/layout.vcxproj.filters \
	./usr/sbin/gencmn \
	./usr/include/unicode/unorm.h \
	./usr/share/doc/libicu-dev/examples/ufortune/resources/root.txt \
	./usr/lib/arm-linux-gnueabihf/icu/4.8.1.1/pkgdata.inc \
	./usr/share/doc/libicu-dev/examples/translit/answers/main_3.cpp \
	./usr/share/doc/libicu-dev/examples/udata/ \
	./usr/include/unicode/utf8.h \
	./usr/share/doc/libicu-dev/examples/legacy/Makefile \
	./usr/include/unicode/parseerr.h \
	./usr/share/doc/libicu-dev/examples/udata/readme.txt \
	./usr/include/unicode/smpdtfmt.h \
	./usr/bin/derb \
	./usr/share/doc/libicu-dev/examples/uciter8/uciter8.vcxproj \
	./usr/include/layout/RunArrays.h \
	./usr/include/unicode/tblcoll.h \
	./usr/share/doc/libicu-dev/examples/uresb/resources.vcxproj \
	./usr/include/unicode/ptypes.h \
	./usr/share/doc/libicu-dev/examples/layout/GnomeFontInstance.cpp \
	./usr/include/unicode/uobslete.h \
	./usr/share/doc/libicu-dev/examples/translit/answers/unaccent.cpp \
	./usr/include/unicode/tmunit.h \
	./usr/lib/arm-linux-gnueabihf/libicutu.so \
	./usr/include/unicode/platform.h \
	./usr/share/doc/libicu-dev/examples/props/readme.txt \
	./usr/share/doc/libicu-dev/examples/msgfmt/answers/main_0.cpp \
	./usr/share/doc/libicu-dev/examples/props/props.sln \
	./usr/include/unicode/rbnf.h \
	./usr/share/doc/libicu-dev/examples/msgfmt/ \
	./usr/include/layout/LayoutEngine.h \
	./usr/include/unicode/uversion.h \
	./usr/include/unicode/schriter.h \
	./usr/share/doc/libicu-dev/examples/ustring/ustring.cpp \
	./usr/include/unicode/search.h \
	./usr/share/doc/libicu-dev/examples/layout/ \
	./usr/share/doc/libicu-dev/examples/layout/gdiglue.h \
	./usr/share/doc/libicu-dev/examples/msgfmt/util.cpp \
	./usr/share/doc/libicu-dev/examples/layout/GDIGUISupport.h \
	./usr/share/doc/libicu-dev/examples/msgfmt/answers/ \
	./usr/share/doc/libicu-dev/examples/ufortune/readme.txt \
	./usr/share/doc/libicu-dev/examples/cal/cal.vcxproj.filters \
	./usr/include/unicode/numfmt.h \
	./usr/share/doc/libicu-dev/examples/rules.mk \
	./usr/share/doc/libicu-dev/examples/legacy/legacy.vcxproj.filters \
	./usr/share/doc/\
"
FILES_libicu48 = " \
	./usr/lib/arm-linux-gnueabihf/libicui18n.so.48.1.1 \
	./usr/lib/arm-linux-gnueabihf/libicudata.so.48.1.1 \
	./usr/lib/arm-linux-gnueabihf/ \
	./usr/share/doc/libicu48/changelog.Debian.gz \
	./usr/lib/arm-linux-gnueabihf/libicutu.so.48 \
	./usr/share/lintian/overrides/libicu48 \
	./usr/share/ \
	./usr/lib/arm-linux-gnueabihf/libicule.so.48.1.1 \
	./usr/lib/arm-linux-gnueabihf/libicuio.so.48 \
	./usr/lib/arm-linux-gnueabihf/libicutu.so.48.1.1 \
	./usr/ \
	./ \
	./usr/lib/ \
	./usr/lib/arm-linux-gnueabihf/libiculx.so.48 \
	./usr/lib/arm-linux-gnueabihf/libicutest.so.48 \
	./usr/lib/arm-linux-gnueabihf/libicuuc.so.48 \
	./usr/share/doc/libicu48/copyright \
	./usr/share/doc/libicu48/NEWS.Debian.gz \
	./usr/share/doc/libicu48/ \
	./usr/lib/arm-linux-gnueabihf/libicutest.so.48.1.1 \
	./usr/lib/arm-linux-gnueabihf/libicuuc.so.48.1.1 \
	./usr/lib/arm-linux-gnueabihf/libicule.so.48 \
	./usr/lib/arm-linux-gnueabihf/libicui18n.so.48 \
	./usr/share/lintian/ \
	./usr/share/lintian/overrides/ \
	./usr/lib/arm-linux-gnueabihf/libiculx.so.48.1.1 \
	./usr/lib/arm-linux-gnueabihf/libicuio.so.48.1.1 \
	./usr/lib/arm-linux-gnueabihf/libicudata.so.48 \
	./usr/share/doc/\
"
#FAKE LICENSE FOR TESTING!!!
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta/COPYING.MIT;md5=3da9cfbcb788c80a0384361b4de20420"
